// RootLayout.tsx

import React from 'react';
import ReduxProvider from './store/ReduxProvider'; // Import ReduxProvider component
import RegistrationChecker from './ui/RegistrationChecker';
import { Inter } from "next/font/google";
import type { Metadata } from "next";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <ReduxProvider>
            <html lang="en">
            <body className={inter.className}>
            <RegistrationChecker>{children}</RegistrationChecker>
            </body>
            </html>
        </ReduxProvider>
    );
};

export default RootLayout;
